### ISSUE TITLE
Video and Audio Issues

### ISSUE THREAD

**Issue by JaCorbett** [prjctrft/mantenuto#89]
Could not see other person's face and could not hear a voice. Own computer was showing video.

<img width="1680" alt="screen shot 2017-12-01 at 1 06 11 pm" src="https://user-images.githubusercontent.com/13542625/33497379-c2dca5a0-d69b-11e7-805a-2239da4fc613.png">

**Comment by hdngr** [comment]
@JaCorbett I am closing this because I don't think it is a techical issue with video calling - I don't think I've implemented robust enough UI/UX to account for handling turning on video, etc.  For instance, if you press "phone" button, it will call the other user even if you are already on a call...  Let me think through this stuff...  

![image](https://user-images.githubusercontent.com/1875033/33728964-0b2d3d30-db31-11e7-8c4e-2eb77cdd5c69.png)
